In [2]:
import numpy as np

In [3]:
##1. Use numpy to test whether none of the elements of a given array is zero

data=np.array([[1,2,1],[4,5,6]])

def testzero(data):
    for row in data:
        for item in row: 
            if item==0:
                print("true")
            else: 
                print("false")

## not sure of the syntax
if (data==0).any():
    print("Array contains a 0")
else:
    print ("Array does not contain 0")
    
data.any(0)  ## why doesn't this work ? 

Array does not contain 0


array([ True,  True,  True], dtype=bool)

In [ ]:
#this doesn't work because it is asking whether there are any Trues inside data along the 0th axis
data.any(0)

In [68]:
##1. Use numpy to create an array with the values 1, 7, 13, 105

data1=np.full((3,3),7)
print(data1)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [5]:
## 1. Use numpy to create an array of 10 zeros,10 ones, 10 fives 

data2=np.zeros((3,10),dtype=int)
data2[1,:]=1
data2[2,:]=5
print(data2)


[[0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1]
 [5 5 5 5 5 5 5 5 5 5]]


In [6]:
##1. Use numpy to create a nxn identity matrix

z=5
data4=np.zeros((z,z),dtype=int)
n=0
for i in data4:
    data4[n,n]=1
    n=n+1
print(data4)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [7]:
## 1. Use numpy to compute the inner product of two given vectors.

x=np.array([1,2,3])
y=np.array([4,5,6])

np.matmul(x,y.T)


32

In [8]:
## 1. Use numpy to convert a given array into a list and then convert it into a list again.

data5=np.array([[1,2,3,4],[5,6,7,8]])

flatdata5=data5.flatten()
print(flatdata5)

reshapeddata5=np.reshape(flatdata5,(2,4))
print(reshapeddata5)



[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]


In [24]:
## 1. Use numpy to get the minimum and maximum value of a given array along the second axis

data5=np.array([[1,2,3,4],[5,6,7,8]])

print(data5)
print(np.min(data5,axis=1))
print(np.max(data5,axis=1))

[[1 2 3 4]
 [5 6 7 8]]
[1 5]
[4 8]


In [10]:
## 1. Use numpy to compute the mean, standard deviation, and variance of a given array along the second axis.

data5=np.array([[1,2,3,4],[5,6,7,8]])

print(data5)
print(np.mean(data5,axis=1))
dev=np.std(data5,axis=1)
var=np.var(data5,axis=1)
print(dev)
print(var)

if (var[0]-(dev[0]**2)) ==0:
    print ("true")
else:
    print ("false")

[[1 2 3 4]
 [5 6 7 8]]
[ 2.5  6.5]
[ 1.11803399  1.11803399]
[ 1.25  1.25]
false


In [57]:
## 1. Write a Python program to count number of occurrences of each value in a given array of non-negative integers (eg. like a histogram)

data6=np.array([[1,2,2,2],[5,2,8,8]])

print(np.count_nonzero(data6==2))
print(np.count_nonzero(data6==2,axis=1))


4
[3 1]


In [67]:
## 1. Write a NumPy program to calculate cumulative product of the elements along a given axis, 
## sum over rows for each of the 3 columns and 
## product over columns for each of the 2 rows of a given 3x3 array (??)

array=np.arange(1,10).reshape(3,3)

print(array)
print(np.cumprod(array,axis=0))

print(np.sum(array,axis=0))



[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[  1   2   3]
 [  4  10  18]
 [ 28  80 162]]
[12 15 18]
